import os
from openai import AzureOpenAI
 
client = AzureOpenAI(
  azure_endpoint = "https://open-ai-xamar-eus.openai.azure.com/openai/deployments/gpt-35-turbo/chat/completions?api-version=2023-09-15-preview",
  api_key="d417163c5acb4267ae45e136561057db",  
  api_version="2023-09-15-preview"
)
 
def ask_question(question, conversation_history=[]):
  """
  This function sends a question to the Azure OpenAI API and returns the answer.

  Args:
      question: The question to be asked.
      conversation_history: A list of dictionaries representing previous interactions (optional).

  Returns:
      The answer generated by the Azure OpenAI API.
  """
  
  # Build the prompt
  prompt = ""
  if conversation_history:
      prompt += "The user has previously asked:\n"
      for item in conversation_history:
          prompt += f"- {item['role']}: {item['content']}\n"
  
  prompt += f"\n**Current User Question:**\n{question}\n"
  prompt += "\n**Instruction:**\nAnswer the question in a comprehensive and informative way, using your knowledge and the conversation history as context.\n"

  # Send the prompt and get the response
  response = client.chat.completions.create(
      model="gpt-35-turbo",  # Adjust model as needed
      prompt=prompt
  )
  
  # Return the answer from the first completion
  return response.choices[0].message.content.strip()

# Example usage
question = "What is the height of the Eiffel Tower?"
conversation_history = [  # Include conversation history if applicable
  {"role": "user", "content": "What is the capital of France?"},
  {"role": "assistant", "content": "The capital of France is Paris."},
]
answer = ask_question(question, conversation_history)
print(f"Question: {question}")
print(f"Answer: {answer}")

